---
title: "First Knit"
author: "Cyndhell Anne Pilarca"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended at Dr. Arcadio Santos National High School, Yes I graduate. English class is more on word, sentences, paper work, communication and interaction to others. While Math is more on computation and numbers, measuring angles. I think the subject that I'm best with is Math when I'm in senior high school I take class ABM which is Accountancy, Business and Management and before I'm always part of the honor class.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I'm using Windows, on scale of 1 to 10 I would rate myself 8.75 like average because I know how to access or use computer but when it comes to a new task sometimes I'm having a hard time to figure out but I will practice hard to know it more. The internet connection at my Home so far so good.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer  
My First Name which is Cyndhell.
  
   
 



## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer  
The Only Thing I want to achieve in life is to be stable and to help my parents and siblings. The college subject I'm interested with is Human Anatomy I really want to know how our body works. The degree I want to achieve is to be Registered Nurse and, Also if I will be given a chance I want to pursue and achieve the degree of Accountancy.
  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




